<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reviews 3</name>
   <tag></tag>
   <elementGuidId>7413c813-3c45-43c8-9c20-516b26835a04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tab-label-reviews-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tab-label-reviews-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0dad04be-399d-4c28-8be3-71f537d01e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data switch</value>
      <webElementGuid>fd4a7c8b-a504-4bf4-bd69-00b684eab231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d31d8b16-634e-4882-a404-747ef188f19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>trigger</value>
      <webElementGuid>d4a1f8a3-c189-40e3-8653-a4ea2c9df607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#reviews</value>
      <webElementGuid>14864f32-fe36-4efb-acf5-d292bbfb15f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-label-reviews-title</value>
      <webElementGuid>42ff2546-ef36-4c53-8236-93fa883d78e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Reviews 3                    </value>
      <webElementGuid>7bd80467-63a0-44e7-9d52-f1575ac6bb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-label-reviews-title&quot;)</value>
      <webElementGuid>cd233ba0-77b9-4cce-84f9-bb0f63d63d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tab-label-reviews-title']</value>
      <webElementGuid>18ffb245-ec51-4e92-b392-5d0ad7f184e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-label-reviews']/a</value>
      <webElementGuid>e01d5dc0-664c-40f5-9ad7-80c84e7d3556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hydration Pocket, Audio Pocket, Waterproof, Lightweight'])[1]/following::a[1]</value>
      <webElementGuid>28c970f4-90d8-474e-bcba-32261d1b2405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Features'])[1]/following::a[1]</value>
      <webElementGuid>a0bc2886-f50b-44b0-8f3b-43a819ba643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write Your Own Review'])[1]/preceding::a[1]</value>
      <webElementGuid>1a001b61-c825-4f84-a441-b47a996c0b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#reviews')])[2]</value>
      <webElementGuid>bbcd1df8-ce1d-48a4-8930-d1ab0ba9d90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/a</value>
      <webElementGuid>b99a388b-c755-4873-8c72-18a1147b6b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#reviews' and @id = 'tab-label-reviews-title' and (text() = '
                        Reviews 3                    ' or . = '
                        Reviews 3                    ')]</value>
      <webElementGuid>6d5f59cd-7e5c-4ad4-a4da-2d06d801f7d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
