<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add to Compare_product-image-photo</name>
   <tag></tag>
   <elementGuidId>1dbffea0-3aa2-46eb-8efd-2eed0ac269df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[3]/div/div[2]/div[3]/div/div/ol/li[5]/div/a/span/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.product-image-container.product-image-container-6 > span.product-image-wrapper > img.product-image-photo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2f64f992-87cd-4b88-9960-3b309741afb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image-photo</value>
      <webElementGuid>b9d000bf-2a45-401f-ada2-0ba33fca5095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qa.magentoprojects.net/media/catalog/product/cache/97ef5faf3eb827bfbbb73a9241833e51/m/b/mb02-gray-0.jpg</value>
      <webElementGuid>7f3d381a-96ee-42bd-b0f6-a3020da35775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>3f462856-0695-42cf-b9d3-3ce091694887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>44d297b8-bf15-42a8-b50e-efadcd6501bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>b3a02396-1433-4145-8086-fa732f0b3689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Fusion Backpack</value>
      <webElementGuid>d0fd407f-6523-4760-9ce0-2c9fc0be78cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;widget block block-static-block&quot;]/div[@class=&quot;block widget block-products-list grid&quot;]/div[@class=&quot;block-content&quot;]/div[@class=&quot;products-grid grid&quot;]/ol[@class=&quot;product-items widget-product-grid&quot;]/li[@class=&quot;product-item&quot;]/div[@class=&quot;product-item-info&quot;]/a[@class=&quot;product-item-photo&quot;]/span[@class=&quot;product-image-container product-image-container-6&quot;]/span[@class=&quot;product-image-wrapper&quot;]/img[@class=&quot;product-image-photo&quot;]</value>
      <webElementGuid>59277632-cefc-42cf-aa03-2b66d08b58a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[2]/div[3]/div/div/ol/li[5]/div/a/span/span/img</value>
      <webElementGuid>b82e6cea-b6ba-4f5f-96c4-11dc5e74e503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Fusion Backpack'])[2]</value>
      <webElementGuid>abaa76e6-38b8-42b5-bc6c-2f9b622b80fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/a/span/span/img</value>
      <webElementGuid>dbc1eb3a-3b59-45c4-8945-3a68c9f03ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://qa.magentoprojects.net/media/catalog/product/cache/97ef5faf3eb827bfbbb73a9241833e51/m/b/mb02-gray-0.jpg' and @alt = 'Fusion Backpack']</value>
      <webElementGuid>ed907107-b74a-4ab5-80c8-d399aaa8fc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Fusion Backpack']</value>
      <webElementGuid>eb71e90c-ec0d-4174-927f-9ed0349a5f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[2]/div[3]/div/div/ol/li[4]/div/a/span/span/img</value>
      <webElementGuid>36df266b-1d7a-4f48-86e2-afd099df0939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Hero Hoodie'])[2]</value>
      <webElementGuid>11392a4c-3d7a-40de-8a52-0f29da546bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a/span/span/img</value>
      <webElementGuid>c6131545-72cf-4cda-a330-ae58ab95df5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://qa.magentoprojects.net/media/catalog/product/cache/97ef5faf3eb827bfbbb73a9241833e51/m/h/mh07-gray_main_2.jpg' and @alt = 'Hero Hoodie']</value>
      <webElementGuid>f0e56795-c2a6-4e0e-9ed4-ed086890b1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hero Hoodie']</value>
      <webElementGuid>8ac46b74-3722-46da-a968-709b1eb175e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
