<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_hero1</name>
   <tag></tag>
   <elementGuidId>63939394-3853-45ef-9df9-af32e1257040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='qs-option-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#qs-option-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1b4989e9-4341-4490-8a5e-a1441f1bcd99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>21a7d046-65a3-4ee8-aebd-8df2195ea77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qs-option-0</value>
      <webElementGuid>b06d9e5a-d9b3-45cf-b61a-48a376768eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0a33f4f7-4a9e-4a6b-93b9-2a6dd3f1dbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> hero1</value>
      <webElementGuid>387dbb6c-0956-40a0-ac63-36ac830310b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qs-option-0&quot;)</value>
      <webElementGuid>119deb68-4411-4277-926b-f2d43261fdf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='qs-option-0']</value>
      <webElementGuid>e587f888-958d-43ee-b1c5-5621800019b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_autocomplete']/ul/li</value>
      <webElementGuid>d0587fe2-6410-4032-ab59-8e7d13e66bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::li[1]</value>
      <webElementGuid>20d325db-4ed4-457b-940e-48771f81f03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::li[1]</value>
      <webElementGuid>c25053c7-b4b3-438b-b618-1b26e3e3cadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search'])[1]/preceding::li[1]</value>
      <webElementGuid>73e308cd-e9ce-48cc-b42a-f2a3574cf59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li</value>
      <webElementGuid>05aa8447-d26e-4fe9-ae9a-f809b9a5251b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'qs-option-0' and (text() = ' hero1' or . = ' hero1')]</value>
      <webElementGuid>6e9d7b82-b827-49c6-a769-81e8b1a87fd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
