<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tees</name>
   <tag></tag>
   <elementGuidId>271e5122-346a-421c-9095-96dac694a8b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-16']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-16 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1f1182b5-7238-4470-85eb-1b4738c33af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tees</value>
      <webElementGuid>c56c9a36-a8e1-4eed-b42c-6d035350bf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-16&quot;)/span[1]</value>
      <webElementGuid>80fe8750-42fa-4642-bc29-09c0155c0892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ui-id-16']/span</value>
      <webElementGuid>817082ea-1143-4a8e-a3f6-3a7c4a9e002f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoodies &amp; Sweatshirts'])[1]/following::span[1]</value>
      <webElementGuid>00f639c6-6c18-46d6-98a4-f04cccfeaa7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jackets'])[1]/following::span[2]</value>
      <webElementGuid>68e2e034-c424-4114-97ab-7351836115a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bras &amp; Tanks'])[1]/preceding::span[1]</value>
      <webElementGuid>25025781-56f4-4565-b215-02a6b1657404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bottoms'])[1]/preceding::span[3]</value>
      <webElementGuid>d20a94bb-2905-440c-b360-a890e4d972b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tees']/parent::*</value>
      <webElementGuid>28790996-b1ab-471d-99b8-f2075990faae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li[3]/a/span</value>
      <webElementGuid>b82b155e-83c9-4895-a3de-b6b8f4b06871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tees' or . = 'Tees')]</value>
      <webElementGuid>5b2abc2a-8fc8-40a0-8eee-eb18505debe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
