<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Set Ascending Direction_product-image-photo</name>
   <tag></tag>
   <elementGuidId>9300ce04-6629-4657-8525-2fab0e6f0307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='product-item-info_160']/a/span/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.product-image-photo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4c62ac9e-3186-4746-bc02-895d03244140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image-photo</value>
      <webElementGuid>c5c28a80-4243-4959-a8e1-7f3efd026c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://qa.magentoprojects.net/media/catalog/product/cache/97ef5faf3eb827bfbbb73a9241833e51/m/h/mh07-gray_main_2.jpg</value>
      <webElementGuid>8d5678e5-0680-4159-aed4-9328cabd5dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>2cfcc9fc-bb26-4e81-bd55-00ae32693092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>240</value>
      <webElementGuid>c55b1e94-78de-41c0-a8e6-fa9c5f3a22c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>85e7a9ad-6bcb-4cae-ba78-2920a686d11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Hero Hoodie</value>
      <webElementGuid>d997dafb-a8fa-4fb3-8a56-390b8147439f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-item-info_160&quot;)/a[@class=&quot;product photo product-item-photo&quot;]/span[@class=&quot;product-image-container product-image-container-160&quot;]/span[@class=&quot;product-image-wrapper&quot;]/img[@class=&quot;product-image-photo&quot;]</value>
      <webElementGuid>b10c0b29-a87a-4d22-be40-a13c4f78f732</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-item-info_160']/a/span/span/img</value>
      <webElementGuid>ab75b820-3f30-4dce-9806-2e4eab9aa190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Hero Hoodie']</value>
      <webElementGuid>a0c71b98-6148-4fff-bb19-2073d5f5b14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>26b01bfb-fbde-4800-b092-1efd76a9597b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://qa.magentoprojects.net/media/catalog/product/cache/97ef5faf3eb827bfbbb73a9241833e51/m/h/mh07-gray_main_2.jpg' and @alt = 'Hero Hoodie']</value>
      <webElementGuid>901a0aa2-e9f7-4949-9fc7-620ddabe8da2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
