<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Best Way_ko_unique_2</name>
   <tag></tag>
   <elementGuidId>bbcfe50f-eecd-447c-90dc-edd2111bb1b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ko_unique_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ko_unique_1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52c8160d-9ef3-4fe9-b548-692273a41f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e9456285-1ec8-4e68-a991-f0481deb96aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f3bb2a13-0027-4ca8-a35e-ccefc3ade767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {'aria-labelledby': 'label_method_' + method.method_code + '_' + method.carrier_code + ' ' + 'label_carrier_' + method.method_code + '_' + method.carrier_code,
                    'checked': element.rates().length == 1 || element.isSelected}, value: method.carrier_code + '_' + method.method_code, checked: element.isSelected</value>
      <webElementGuid>a9b74186-b3d9-4798-8645-e681878beea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label_method_bestway_tablerate label_carrier_bestway_tablerate</value>
      <webElementGuid>c2010378-d483-45d4-a016-722ef116ecc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>tablerate_bestway</value>
      <webElementGuid>8e7a7612-4b2e-40a9-a9ea-54f62d54e129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ko_unique_1</value>
      <webElementGuid>15d8162a-86e5-421a-81f8-e772e187d93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-shipping-method-load&quot;)/table[@class=&quot;table-checkout-shipping-method&quot;]/tbody[1]/tr[@class=&quot;row&quot;]/td[@class=&quot;col col-method&quot;]/input[@class=&quot;radio&quot;]</value>
      <webElementGuid>fca52d07-c10f-4eb2-8d3a-c229569829d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>tablerate_bestway</value>
      <webElementGuid>22bf6746-e9b8-41ad-af36-224d8865e9bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ko_unique_1']</value>
      <webElementGuid>869c15ef-5985-4aaf-b485-922ffd360461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-method-load']/table/tbody/tr/td/input</value>
      <webElementGuid>90fd742c-f645-43be-b890-cdf99452690e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>f5bc8b79-4899-40ff-ab7b-d9c2ae73fb53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ko_unique_1' and @checked = 'tablerate_bestway']</value>
      <webElementGuid>4280e271-ca03-492b-aa09-360a01dd94ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ko_unique_1']</value>
      <webElementGuid>ce66108f-291e-4b65-8a86-b40f84dafae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ko_unique_2']</value>
      <webElementGuid>a5f5804a-8259-4d60-a90f-896080fe7296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-shipping-method-load']/table/tbody/tr[2]/td/input</value>
      <webElementGuid>42c923c5-b7e3-4c2a-8db7-31cc0baed17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>6796db4c-056b-430d-8370-6a2378ed663d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @checked = 'flatrate_flatrate' and @name = 'ko_unique_2']</value>
      <webElementGuid>9f1e862b-e72a-47b4-b640-1c59c9cc0e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ko_unique_2']</value>
      <webElementGuid>51b56c3e-92e8-4ff9-87fc-63b003b0d558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
