name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '9.3.1'
          projectPath: '${{ github.workspace }}/MagentoWebApp/MagentoWebApp.prj'
          args: 'katalonc -noSplash -runMode=console -projectPath="C:\Users\kashyap.dave\KatalonStudio\MagentoWebApp\MagentoWebApp.prj" -retry=0 -testSuitePath="Test Suites/New Test Suite" -browserType="Chrome" -executionProfile="default" -apiKey="7bbd1031-e066-448b-b87e-bb1acbd611be" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'