name: Katalon CI

on:
  push:
    branches:
      - master

jobs:
  katalon_test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Katalon Studio
        uses: katalon-studio/action-setup@v2
        with:
          version: '9.3.1'
          email: ${{ secrets.KATALON_EMAIL }}
          password: ${{ secrets.KATALON_PASSWORD }}

      - name: Execute Katalon Tests
        run: |
          cd 'C:\Users\kashyap.dave\KatalonStudio\MagentoWebApp'
          katalonc.exe -noSplash -runMode=console -projectPath="MagentoWebApp\MagentoWebApp.prj" -retry=0 -testSuitePath="Test Suites/New Test Suite"

      - name: Upload Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: katalon-report
          path: C:\Users\kashyap.dave\KatalonStudio\MagentoWebApp\Reports